[package]
name = "blue-recorder-core"
version = "0.1.0"
edition = "2021"

[features]
cmd = []
gtk = ["adw", "chrono", "glib", "subprocess"]

[dependencies]
adw = { version = "0.2.1", package = "libadwaita", features = ["gtk_v4_6"], optional = true }
anyhow = "1.0.86"
chrono = { version = "0.4.19", optional = true }
ffmpeg-sidecar = "1.1.0"
glib = { version = "0.10.3", optional = true }
open = "5.1.4"
subprocess = {version = "0.2.6", optional = true }
tempfile = "3.10.1"
